string disk # move disk..
string tower # ..to tower
geometry_msgs/Point floating_point # if tower=="floating",
                                   # try to reach this position
---
bool success # if success==False, refer to reason
int8 reason # -128: aborted/preempted, 0: none, 1: goal not valid,
            # 2: disk unreachable, 4: tower unreachable,
            # 8: point unreachable
---
float32 percent
geometry_msgs/Transform wrist # maybe?